name: train-my-model
 
on: [push]
 
jobs:
  run:
    runs-on: [ubuntu-latest]
 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
 
      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
 
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
         
       - 
        name: BUILD DOCKER IMAGE 
        run: |
          docker build -t wine_clf:with-batch .
      
      - 
        name: run DOCKER 
        run: |
          docker run --rm -p 80:80 wine_clf:with-batch
      -
        name: Test with pytest
        run: |
          cd app/
          pytest
          
      -
        name: CURL 
        run: |
          cd wine-example/
          curl -X POST http://localhost:81/predict \
          -d @./wine-examples/batch_1.json \
          -H "Content-Type: application/json" >>report.md     
         
          cml send-comment report.md
