name: CI-workflow
on: [push]


jobs :
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v2
        with:
           python-version: '3.7'
      - uses: iterative/setup-cml@v1
      
      - name: install dependecies
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          
          
      -
        name: Test with pytest
        run: |
          cd app/
          pytest
          
      -
        name: CURL 
        run: |
          cd wine-examples/
          curl -X POST http://localhost:80/predict \
          -d @./batch_1.json \
          -H "Content-Type: application/json"  >>report.md       
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
         
          cml send-comment report.md
